# Generated by Django 4.1.5 on 2025-07-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_signin_api_input_signin_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='trading_account',
        ),
    ]
