# Generated by Django 4.1.5 on 2025-07-27 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_marketdata_brokerageintegration_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('DATA_FETCH', 'Data Fetch'), ('INDICATOR_CALC', 'Indicator Calculation'), ('SIGNAL_GENERATED', 'Signal Generated'), ('TRADE_EXECUTED', 'Trade Executed'), ('TRADE_FAILED', 'Trade Failed'), ('STRATEGY_START', 'Strategy Started'), ('STRATEGY_STOP', 'Strategy Stopped'), ('ERROR', 'Error'), ('INFO', 'Info')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.strategy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
