# Generated by Django 4.1.5 on 2025-07-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_botlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsetup',
            name='trade_direction',
            field=models.CharField(choices=[('BUY', 'Buy Only'), ('SELL', 'Sell Only'), ('BOTH', 'Buy & Sell')], default='BOTH', max_length=4),
        ),
    ]
