# Generated by Django 4.1.5 on 2025-07-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tradingsetup_trade_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='stop_loss_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stop loss percentage (e.g., 2.00 for 2%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='take_profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Take profit percentage (e.g., 5.00 for 5%)', max_digits=5, null=True),
        ),
    ]
